name: android Platform Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/build
  ARTIFACT_DIR: ${{ github.workspace }}/artifacts

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86_64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Cross Tools
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build

    - name: Setup NDK
      uses: android-actions/setup-android@v2

    - name: Configure
      run: |
        cmake -B $BUILD_DIR/android-${{ matrix.abi }} \
          -DCMAKE_TOOLCHAIN_FILE=cross_toolchain.cmake \
          -DCROSS_TARGET=Android \
          -DCROSS_ARCH=${{ matrix.abi }} \
          -DANDROID_ABI=${{ matrix.abi }} \
          -G Ninja

    - name: Build
      run: cmake --build $BUILD_DIR/android-${{ matrix.abi }}  -- -j1

    - name: Package
      run: |
        mkdir -p $ARTIFACT_DIR/android-${{ matrix.abi }}
        cp $BUILD_DIR/android-${{ matrix.abi }}/lib/*.so $ARTIFACT_DIR/android-${{ matrix.abi }}/

    - uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.abi }}-binaries
        path: $ARTIFACT_DIR/android-${{ matrix.abi }}/

